### ISSUE TITLE
SCSS Linting: Mergeable selectors

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#665]
Right now, we are [ignoring the MergeableSelector linter on SCSS Lint](https://github.com/Gapminder/vizabi/blob/develop/.scss-lint.yml#L10): 

```yaml

MergeableSelector:
    enabled: false
```

If we remove that exception from `.scss-lint.yml` (removing the lines or setting `enabled` to `true`) and run `gulp build`, we see that a bunch of errors are reported on the console:

![image](https://cloud.githubusercontent.com/assets/3584238/10453583/ac164286-71ad-11e5-81ad-59d2fed85b20.png)

This rule basically analyses the code and reports when there are two selectors that can be merged. **Example:**

```css
.vzb-label {
  background: #c00;
}

.vzb-label {
  border: 0;
}
```

should be merged and become:

```css
.vzb-label {
  background: #c00;
  border: 0;
}
```

We should remove the exception and fix the linting errors :)
