### ISSUE TITLE
SCSS Linting: Declaration Order and Property Sort Order

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#666]
Right now, we are [ignoring the DeclarationOrder and PropertySortOrder linter on SCSS Lint](https://github.com/Gapminder/vizabi/blob/develop/.scss-lint.yml#L4): 

```yaml

DeclarationOrder:
    enabled: false
#...
PropertySortOrder:
    enabled: false
```

If we remove those exceptions from `.scss-lint.yml` (removing the lines or setting `enabled` to `true`) and run `gulp build`, we see that a bunch of errors are reported on the console:

![image](https://cloud.githubusercontent.com/assets/3584238/10453836/f54cc6bc-71af-11e5-96f1-2143f79d3585.png)

The `DeclarationOrder` rule basically determines that we should first add `@extend` declarations, then `@include`, then regular properties, then nested selectors. The `PropertySortOrder` rule determines that properties should be sorted alphabetically

**Example 1** [Checkout the `DeclarationOrder` example on the SCSS Coding Styleguide](https://github.com/Gapminder/vizabi/wiki/SCSS-Coding-Styleguide#ordering-of-property-declarations)

**Example 2** The `PropertySortOrder` determines that 

```css
.vzb-label {
  width: 100px;
  background-color: #c00;
  height: 10px;
}
```

should become

```css
.vzb-label {
  background-color: #c00;
  height: 10px;
  width: 100px;
}
```

We should remove the two exceptions and fix the linting errors :)
